web_dashboard/logistics/urls.py
from django.urls import path
from . import views

app_name = 'logistics'

urlpatterns = [
    # Departures
    path('', views.DepartureListView.as_view(), name='all'),
    path('create/', views.DepartureCreateView.as_view(), name='create'),
    path('<int:pk>/', views.DepartureDetailView.as_view(), name='read'),
    path(
        '<int:pk>/update/',
        views.DepartureUpdateView.as_view(),
        name='update'
    ),
    path(
        '<int:pk>/delete/',
        views.DepartureDeleteView.as_view(),
        name='delete'
    ),
]

web_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('account/', include('web_dashboard.users.urls')),
    path('', include('web_dashboard.custom_auth.urls')),
    # path(f'{settings.WEBHOOK_URL}/', include('web_dashboard.bot_api.urls')),
    path('requests/', include('web_dashboard.search_requests.urls')),
    path('logistics/', include('web_dashboard.logistics.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

web_dashboard/logistics/models.py
from django.db import models
from django.contrib.gis.db.models import PointField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from location_field.models.spatial import LocationField

from web_dashboard.users.models import CustomUser
from web_dashboard.search_requests.models import GetFieldsMixin
from web_dashboard.search_requests import models as models_sr


class Departure(GetFieldsMixin, models.Model):
    """Class represents departure."""
    search_request = models.ForeignKey(
        models_sr.SearchRequest,
        related_name='departures',
        verbose_name=_('Search Request'),
        on_delete=models.CASCADE
    )

    class StatusVerbose(models.TextChoices):
        """Search request status choices."""
        OPEN = 'O', _('Open')
        ACTIVE = 'A', _('Active')
        CLOSED = 'C', _('Closed')

    status = models.CharField(
        _('Status'),
        max_length=1,
        choices=StatusVerbose.choices,
        default=StatusVerbose.OPEN,
    )

    created_at = models.DateTimeField(
        _('Created at'),
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        _('Updated at'),
        auto_now=True
    )

    def __str__(self) -> str:
        """Representation of a single instance."""
        return f'ID {self.id} ({self.get_status_display()})'

    def get_absolute_url(self) -> str:
        """Return absolute url to the object."""
        return reverse('logistics:read', kwargs={'pk': self.pk})


class Crew(GetFieldsMixin, models.Model):
    """Class represent crew."""
    departure = models.ForeignKey(
        Departure,
        related_name='crews',
        verbose_name=_('Departure'),
        on_delete=models.CASCADE,
    )

    title = models.CharField(
        _('Title'),
        max_length=32,
        help_text=_("Required 32 characters or fewer."),
        blank=False,
        null=False,
    )

    class StatusVerbose(models.TextChoices):
        """Crew status choices."""
        AVAILABLE = 'A', _('Available')
        ON_MISSION = 'M', _('On mission')
        RETURNING = 'R', _('Returning')
        COMPLETED = 'C', _('Completed')

    status = models.CharField(
        _('status'),
        max_length=1,
        choices=StatusVerbose.choices,
        default=StatusVerbose.AVAILABLE,
    )

    driver = models.ForeignKey(
        CustomUser,
        verbose_name=_('Driver'),
        related_name='crews',
        on_delete=models.CASCADE,
    )

    passengers_max = models.IntegerField(
        _('Max passengers'),
        blank=False,
        null=False,
    )

    passengers = models.ManyToManyField(
        CustomUser,
        verbose_name=_('Passengers'),
        related_name='passenger_crews',
        blank=True,
    )

    pickup_location = PointField(
        _('Pickup location'),
        blank=False,
        null=False,
    )

    pickup_datetime = models.DateTimeField(
        _('Pickup at'),
        blank=False,
        null=False,
    )

    departure_datetime = models.DateTimeField(
        _('Departure at'),
        blank=True,
        null=True,
    )

    return_datetime = models.DateTimeField(
        _('Return at'),
        blank=True,
        null=True,
    )

    created_at = models.DateTimeField(
        _('Created at'),
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        _('Updated at'),
        auto_now=True
    )

    def __str__(self) -> str:
        """Representation of a single instance."""
        return f'{self.title}-{self.id} ({self.get_status_display()})'

    def get_absolute_url(self) -> str:
        """Return absolute url to the object."""
        return reverse('logistics:crew_read', kwargs={'pk': self.pk})

    async def aaccept_join_request(self, join_request):
        """Async accept JoinRequest to crew and change it status."""
        if join_request.crew != self:
            raise ValueError("This join request does not belong to this crew.")
        if await self.passengers.acount() >= self.passengers_max:
            raise ValueError("The crew has already reached the maximum number of passengers.")  # noqa: E501

        join_request.status = JoinRequest.StatusVerbose.ACCEPTED
        await join_request.asave()
        await self.passengers.aadd(join_request.passenger)
        await self.asave()

    async def areject_join_request(self, join_request):
        """Async reject JoinRequest and change it status and remove it."""
        if join_request.crew != self:
            raise ValueError("This join request does not belong to this crew.")
        join_request.status = JoinRequest.StatusVerbose.REJECTED
        await join_request.asave()
        await self.passengers.aremove(join_request.passenger)
        await self.asave()


class JoinRequest(models.Model):
    """Model to represent join requests from passengers to crews."""
    passenger = models.ForeignKey(
        CustomUser,
        verbose_name=_('Passenger'),
        related_name='join_requests',
        on_delete=models.CASCADE,
    )

    crew = models.ForeignKey(
        Crew,
        verbose_name=_('Crew'),
        related_name='join_requests',
        on_delete=models.CASCADE,
    )

    request_time = models.DateTimeField(
        _('Request Time'),
        auto_now_add=True,
    )

    class StatusVerbose(models.TextChoices):
        """Pedestrian status choices."""
        PENDING = 'P', _('Pending')
        ACCEPTED = 'A', _('Accepted')
        REJECTED = 'R', _('Rejected')

    status = models.CharField(
        _('status'),
        max_length=1,
        choices=StatusVerbose.choices,
        default=StatusVerbose.PENDING,
    )

    class Meta:
        unique_together = ('passenger', 'crew')

    @property
    def emoji(self):
        match self.status:
            case self.StatusVerbose.PENDING:
                return "🟡"
            case self.StatusVerbose.ACCEPTED:
                return "🟢"
            case  self.StatusVerbose.REJECTED:
                return "🔴"
        return ""

    def __str__(self):
        """String representation."""
        return f'{self.passenger} ({self.get_status_display()}) -> {self.crew}'  # noqa: E501


class Task(GetFieldsMixin, models.Model):
    """Define a task for a SearchRequest."""
    departure = models.ForeignKey(
        Departure,
        related_name='tasks',
        verbose_name=_('Departure'),
        on_delete=models.CASCADE
    )

    title = models.CharField(
        _('Title'),
        max_length=32,
        help_text=_("Required 32 characters or fewer."),
        blank=False,
        null=False,
    )

    address = models.CharField(
        _('Address'),
        max_length=128,
        help_text=_("Required 128 characters or fewer."),
        blank=False,
        null=False,
    )

    # TODO: Coordinates from address or vice-versa
    coordinates = LocationField(
        verbose_name=_('Coordinates'),
        based_fields=['address'],
        zoom=8,
    )

    description = models.TextField(
        _('Description'),
        blank=True,
        null=True,
    )

    created_at = models.DateTimeField(
        _('Created at'),
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        _('Updated at'),
        auto_now=True
    )

    def __str__(self) -> str:
        """Representation of a single instance."""
        return f'{self.title} ({self.coordinates.coords})'

web_dashboard/logistics/forms.py
# from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .import models


class TaskForm(ModelForm):
    class Meta:
        model = models.Task
        fields = '__all__'
        # widgets = {
        #     'search_request': forms.HiddenInput(),
        # }


TaskFormSet = inlineformset_factory(models.Departure, models.Task,
                                    form=TaskForm, extra=1,)

web_dashboard/logistics/views.py
from django.shortcuts import render
from django.db import transaction
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from . import models, filters, forms


class DepartureBaseView(SuccessMessageMixin, View):
    """Base view for a Departure model."""
    model = models.Departure
    fields = '__all__'
    success_url = reverse_lazy('logistics:all')
    context_object_name = "departure"


class DepartureListView(DepartureBaseView):
    """List all Crews view."""
    template = 'logistics/departure_list.html'

    # @overide
    def get(self, request, *args, **kwargs):
        """Return tasks index."""
        departures = models.Departure.objects.all()
        departures_filtered = filters.DepartureFilter(
            request.GET, queryset=departures, request=request
        )
        return render(
            request, self.template, {'filter': departures_filtered}
        )


class DepartureFormValidMixin:
    """Mixin with defined form_valid() method."""

    def form_valid(self, form):
        """Extend validation on TaskFormSet instances."""
        context = self.get_context_data()
        tasks = context['tasks']
        with transaction.atomic():
            # form.instance.departure = self.request.departure
            self.object = form.save()

            if tasks.is_valid():
                tasks.instance = self.object
                tasks.save()
            return super().form_valid(form)


class DepartureCreateView(DepartureFormValidMixin,
                          DepartureBaseView,
                          CreateView):
    """Departure create view."""
    success_message = _('Departure succussfully created')

    # @overide
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['tasks'] = forms.TaskFormSet(self.request.POST)
        else:
            context['tasks'] = forms.TaskFormSet()
        return context


class DepartureDetailView(DepartureBaseView, DetailView):
    """Departure detail view."""


class DepartureUpdateView(DepartureFormValidMixin,
                          DepartureBaseView,
                          UpdateView):
    """Departure update view."""
    success_message = _('Departure succussfully updated')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['tasks'] = forms.TaskFormSet(self.request.POST,
                                                 instance=self.object)
        else:
            context['tasks'] = forms.TaskFormSet(instance=self.object)
        return context


class DepartureDeleteView(DepartureBaseView, DeleteView):
    """Departure delete view."""
    success_message = _('Departure succussfully deleted')

templates/logistics/departure_confirm_delete.html
{% extends 'base_logged.html' %}
{% load django_bootstrap5 i18n %}

{% block content %}
	<div><a href="{% url 'logistics:all' %}">{% trans 'Back' %}</a></div>
	<h1>{% trans 'Deletion' %}</h1>
	<div>{% trans 'Are you sure you want to delete' %}: <b class="text-danger">{{ object }}</b>?</div>
	<form action="" method="POST">
			{% csrf_token %}
			{{ form }}
			<input type="submit" value="{% trans 'Confirm' %}">
	</form>
{% endblock %}

templates/logistics/departure_detail.html
{% extends 'base_logged.html' %}
{% load django_bootstrap5 i18n %}

{% block content %}
<div>
	<a href="{% url 'logistics:all' %}">{% trans 'Back' %}</a>
	<h1 class="text-center">{% trans 'Departure' %}</h1>
	<h2 class="">ID: {{ object.id }} | Status: {{ object.get_status_display }}</h2>
	<div>
		<a class="btn btn-primary" href="{% url 'logistics:update' object.id %}">{% trans 'Update' %}</a>
		<a class="btn btn-danger" href="{% url 'logistics:delete' object.id %}">{% trans 'Delete' %}</a>
	</div>
</div>


<div>
	<table class="table table-dark table-striped">
		<tr>
			<th>{% trans 'Description' %}</th>
			<th>{% trans 'Value' %}</th>
		</tr>
		{% for label, value in object.get_fields %}
			<tr>
				<td>{{ label }}</td>
				<td>{{ value }}</td>
			</tr>
		{% endfor %}	
	</table>
</div>

		<div>
			<h2>{% trans 'Tasks' %}:</h2>
			{% with tasks=object.tasks.all %}
				{% if tasks %}
					<table class="table table-dark table-striped">
						<tr>
							<th>ID</th>
							<th>{% trans 'Title' %}</th>
							<th>{% trans 'Address' %}</th>
							<th>{% trans 'Coordinates' %}</th>
							<th>{% trans 'Description' %}</th>
						</tr>
						{% for task in tasks %} 
							<tr>
									<td>{{ task.id }}</a></td>
									<td>{{ task.title }}</td>
									<td>{{ task.address }}</td>
									<td>{{ task.coordinates.coords }}</td>
									<td>{{ task.description }}</td>
							</tr>
						{% endfor %}
					</table>
				{% endif %}
			{% endwith %}
		</div>
{% endblock %}

templates/logistics/departure_form.html
{% extends 'base_logged.html' %}
{% load django_bootstrap5 i18n crispy_forms_tags static %}


{% block content %}
<div>
	<a href="{% url 'logistics:all' %}">{% trans 'Back' %}</a>
	<h1 class="text-center">{% trans 'Create departure' %}</h1>
</div>

<div>
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<table class="table">
			{{ form|crispy }}
		</table>

		<b>{% trans 'Tasks' %}</b>
		<table>
			{{ tasks.management_form|crispy }}

			{% for form in tasks.forms %}
				<tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
					{% for field in form.visible_fields %}
					<td>
						{# Include the hidden fields in the form #}
						{% if forloop.first %}
							{% for hidden in form.hidden_fields %}
								{{ hidden }}
							{% endfor %}
						{% endif %}

						{{ field.errors.as_ul }}
						{{ field|as_crispy_field }}
					</td>
					{% endfor %}
				</tr>
			{% endfor %}
		</table>

		<input type="submit" value="{% trans 'Save' %}">
	</form>
</div>

<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
	$('.formset_row-{{ formset.prefix }}').formset({
		addText: '{% trans "add another" %}',
		deleteText: '{% trans "delete" %}',
		prefix: '{{ formset.prefix }}',
	})
</script>
{% endblock %}

templates/logistics/departure_list.html
{% extends 'base_logged.html' %}

{% load django_bootstrap5 i18n %}

{% block content %}
<div>
	<h1 class='text-center'>{% trans 'Logistics' %}</h1>
	<div><a class="btn btn-primary" href="{% url 'logistics:create' %}">{% trans 'Create departure' %}</a></div>
</div>

<div class="m-3">
	<form class="form m-0" action="" method="get">
		{{ filter.form.as_table }}
		<input type="submit" name="filter" value="{% translate 'Show' %}">
	</form>
</div>

<h1 class=''>{% trans 'Departures Total' %}: {{ filter.qs|length }}</h1>
<div>
	<table class="table table-dark table-striped">
			<th>ID</th>
			<th>{% trans 'Title' %}</th>
			<th>{% trans 'Status' %}</th>
			<th>{% trans 'Crews' %}</th>
			<th>{% trans 'Update' %}</th>
			<th>{% trans 'Delete' %}</th>
		{% for departure in filter.qs %}
		<tr>
			<td>{{ departure.id }}</td>
			<td><a href="{% url 'logistics:read' departure.id %}">{{ departure }}</a></td>
			<td>{{ departure.get_status_display }}</td>
			{% with crews=departure.crews %}
			<td>{% if crews %}{# Notification symbol #}<a href="#">{{ crews.count }}</a>{% else %}<span class="text-danger">{{ crews }}</span>{% endif %}</td>
			{% endwith %}
			<td><a href="{% url 'logistics:update' departure.id %}">{% trans 'Update' %}</a></td>
			<td><a href="{% url 'logistics:delete' departure.id %}">{% trans 'Delete' %}</a></td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}