web_dashboard/logistics/urls.py
from django.urls import path
from . import views

app_name = 'logistics'

urlpatterns = [
    # Departures
    path('', views.DepartureListView.as_view(), name='all'),
    path('create/', views.DepartureCreateView.as_view(), name='create'),
    path('<int:pk>/', views.DepartureDetailView.as_view(), name='read'),
    path(
        '<int:pk>/update/',
        views.DepartureUpdateView.as_view(),
        name='update'
    ),
    path(
        '<int:pk>/delete/',
        views.DepartureDeleteView.as_view(),
        name='delete'
    ),
]

web_dashboard/search_requests/urls.py
from django.urls import path
from . import views

app_name = 'search_requests'

urlpatterns = [
    # Search Requests
    path('', views.SearchRequestListView.as_view(), name='all'),
    path('create/', views.SearchRequestCreateView.as_view(), name='create'),
    path('<int:pk>/', views.SearchRequestDetailView.as_view(), name='read'),
    path(
        '<int:pk>/update/',
        views.SearchRequestUpdateView.as_view(),
        name='update'
    ),
    path(
        '<int:pk>/delete/',
        views.SearchRequestDeleteView.as_view(),
        name='delete'
    ),

    # Surveys
    path(
        '<int:pk>/sv/create/',
        views.SurveyCreateView.as_view(),
        name='sv_create'
    ),
    path(
        'sv/<int:pk>/',
        views.SurveyDetailView.as_view(),
        name='sv_read'
    ),
    path(
        'sv/<int:pk>/update/',
        views.SurveyUpdateView.as_view(),
        name='sv_update'
    ),
    path(
        'sv/<int:pk>/delete/',
        views.SurveyDeleteView.as_view(),
        name='sv_delete'
    ),
]

web_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('account/', include('web_dashboard.users.urls')),
    path('', include('web_dashboard.custom_auth.urls')),
    # path(f'{settings.WEBHOOK_URL}/', include('web_dashboard.bot_api.urls')),
    path('requests/', include('web_dashboard.search_requests.urls')),
    path('logistics/', include('web_dashboard.logistics.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

web_dashboard/users/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    # path('create/', views.CustomUserCreateView.as_view(), name='create'),
    # path('<int:pk>/', views.CustomUserDetailView.as_view(), name='read'),
    path(
        'update/',
        views.CustomUserUpdateView.as_view(),
        name='update'
    ),
    path(
        'delete/',
        views.CustomUserDeleteView.as_view(),
        name='delete'
    ),
]

templates/components/formset.html
{% load crispy_forms_tags static %}

<table>
	{{ formset.management_form|crispy }}

	{% for form in formset.forms %}
		<tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
			{% for field in form.visible_fields %}
			<td>
				{# Include the hidden fields in the form #}
				{% if forloop.first %}
					{% for hidden in form.hidden_fields %}
						{{ hidden }}
					{% endfor %}
				{% endif %}

				{{ field.errors.as_ul }}
				{{ field|as_crispy_field }}
			</td>
			{% endfor %}
		</tr>
	{% endfor %}
</table>

<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
	$('.formset_row-{{ formset.prefix }}').formset({
		addText: '{% trans "add another" %}',
		deleteText: '{% trans "delete" %}',
		prefix: '{{ formset.prefix }}',
	})
</script>

templates/components/logout.html
{% load i18n django_bootstrap5 %}

<form action="{% url 'logout' %}" method="post" class="form mb-0">
	{% csrf_token %}

	{% translate 'logout'|capfirst as button_name %}

	{% bootstrap_button button_type="submit" content=button_name button_class="btn-link nav-link" %}
</form>

templates/components/navbar.html
{% load django_bootstrap5 i18n static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
		<!-- LOGO -->
		<a class="navbar-brand" href="{% url 'index' %}">
			<img src="{% static '/logo.png' %}" alt="Logo" width="40" height="40" class="d-inline-block align-text-top">
    </a>

		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<!-- Home -->
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'index' %}">{% trans 'home'|capfirst %}</a>
				</li>

				<!-- Group manager <li class="nav-item"><a class="nav-link" href="#">{% trans "group manager"|capfirst %}</a></li> -->

				<!-- Account manager <li class="nav-item"><a class="nav-link" href="#">{% trans "account manager"|capfirst %}</a></li>-->

				<!-- Requests -->
				<li class="nav-item">
					<a class="nav-link" href="{% url 'search_requests:all' %}">{% trans "requests"|capfirst %}</a>
				</li>

				<!-- Logistics manager-->
				<li class="nav-item">
					<a class="nav-link" href="{% url 'logistics:all' %}">{% trans "logistics manager"|capfirst %}</a>
				</li>

				<!-- Reports -->
				<li class="nav-item">
					<a class="nav-link" href="#">{% trans "reports"|capfirst %}</a>
				</li>

				<!-- Tools -->
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						{% trans 'tools'|capfirst %}
					</a>
					<ul class="dropdown-menu">
						<li><a class="dropdown-item" href="#">{% trans 'Telegram bot "Smart search"' %}</a></li>
						<li><a class="dropdown-item" href="#">{% trans 'Request coordinates' %}</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item" href="#">{% trans 'Compas-director' %}</a></li>
					</ul>
				</li>

				<!-- Combine account actions as a list? -->
				<!-- Account-->
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account:update' %}">{% trans "Account"|capfirst %}</a>
				</li>

				<!-- Logout -->
				<li class="nav-item">{% include 'components/logout.html' %} </li>
			</ul>

			<!-- Search -->
			<form class="d-flex mb-0" role="search">
				<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-success" type="submit">{% trans 'search'|capfirst %}</button>
			</form>

		</div>
  </div>
</nav>